### ISSUE TITLE
Dismiss second VC

### ISSUE THREAD

**Issue by sbuzoianu** [mariusjcb/xcode-medium-modalViews#1]
Cum facem sa dezactivam cel de-al doilea VC - modalul care a fost incarcat la tap?

**Comment by mariusjcb** [comment]
Am facut un articol despre asta: https://medium.com/@mariusilie/dismiss-modal-uiviewcontrollers-b8d101d5c13#.ieh4r41gr

Proiectul de git: https://github.com/mariusjcb/xcode-medium-modalViews/tree/dismissViewControllerAnimated
